AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge global endpoints example
Transform: AWS::Serverless-2016-10-31
Parameters:
  pRegion1:
    Type: String
  pRegion2:
    Type: String
Resources:
  GlobalTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      Replicas:
        - Region: !Ref pRegion1
        - Region: !Ref pRegion2
      StreamSpecification:
        StreamViewType: NEW_IMAGE
Outputs:
  outGlobalTable:
    Value: !GetAtt GlobalTable.Arn