AWSTemplateFormatVersion: '2010-09-09'
Description: EventBridge global endpoints example
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: !Ref pFnMemory
    Runtime: python3.9
    Timeout: !Ref pFnTimeout
Parameters:
  pName:
    Type: String
  pFnMemory:
    Type: Number
  pFnTimeout:
    Type: Number
Resources:
  # EventBridge
  Bus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Ref pName
  Rule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref pName
      EventPattern:
        detail:
          type: ["demo"]
      State: ENABLED
      Targets:
        - Id: lambda
          Arn: !GetAtt Fn.Arn
  # Lambda
  FnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/service-role/'
      Policies:
        - PolicyName: cloudwatch-insights
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: '*'
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:log-group:*:*'
  Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: fn.handler
      Role: !GetAtt FnRole.Arn
  FnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Fn}'
      RetentionInDays: 7
  FnPerm:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Fn.Arn
      Principal: events.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !GetAtt Rule.Arn
Outputs:
  outBus:
    Value: !GetAtt Bus.Arn
  outFn:
    Value: !Ref Fn